import 'dotenv/config';
import { db } from './index';
import { states, cities, deliveryPartners } from './schema';
import { eq } from 'drizzle-orm';

export interface LocationStateSeed {
  name: string;
  code: string;
  cities: string[];
}

export const ALL_INDIA_LOCATIONS: LocationStateSeed[] = [
  {
    name: 'Andaman and Nicobar Islands',
    code: 'AN',
    cities: [
      'Port Blair',
      'Havelock Island',
      'Neil Island',
      'Diglipur',
      'Mayabunder',
      'Rangat',
      'Car Nicobar',
      'Hut Bay',
      'Garacharma',
      'Bambooflat',
    ],
  },
  {
    name: 'Andhra Pradesh',
    code: 'AP',
    cities: [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kakinada',
      'Rajamahendravaram (Rajahmundry)',
      'Tirupati',
      'Kadapa',
      'Anantapur',
      'Eluru',
      'Vizianagaram',
      'Ongole',
      'Nandyal',
      'Machilipatnam',
      'Adoni',
      'Tenali',
      'Proddatur',
      'Chittoor',
      'Hindupur',
      'Bhimavaram',
      'Madanapalle',
      'Guntakal',
      'Srikakulam',
      'Dharmavaram',
      'Gudivada',
      'Narasaraopet',
      'Tadipatri',
      'Mangalagiri',
      'Tadepalligudem',
      'Amaravati',
      'Chilakaluripet',
      'Yemmiganur',
      'Kadiri',
      'Tanuku',
      'Amalapuram',
    ],
  },
  {
    name: 'Arunachal Pradesh',
    code: 'AR',
    cities: [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Along (Aalo)',
      'Tezu',
      'Roing',
      'Namsai',
      'Changlang',
      'Khonsa',
      'Seppa',
      'Yingkiong',
      'Anini',
      'Bhalukpong',
      'Dirang',
    ],
  },
  {
    name: 'Assam',
    code: 'AS',
    cities: [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Bongaigaon',
      'Karimganj',
      'Sivasagar',
      'Goalpara',
      'Dhubri',
      'North Lakhimpur',
      'Diphu',
      'Barpeta',
      'Golaghat',
      'Hailakandi',
      'Hojai',
      'Mangaldai',
      'Kokrajhar',
      'Duliajan',
      'Digboi',
      'Lanka',
      'Rangia',
      'Nalbari',
      'Lumding',
    ],
  },
  {
    name: 'Bihar',
    code: 'BR',
    cities: [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Danapur',
      'Bettiah',
      'Saharsa',
      'Sasaram',
      'Hajipur',
      'Dehri',
      'Siwan',
      'Motihari',
      'Nawada',
      'Bagaha',
      'Buxar',
      'Kishanganj',
      'Sitamarhi',
      'Jamalpur',
      'Jehanabad',
      'Aurangabad',
      'Samastipur',
      'Madhubani',
      'Bhabua',
      'Supaul',
      'Madhepura',
    ],
  },
  {
    name: 'Chandigarh',
    code: 'CH',
    cities: [
      'Chandigarh',
      'Manimajra',
      'Sector 17',
      'Sector 22',
      'Sector 35',
      'Sector 43',
      'Industrial Area Phase 1',
      'Industrial Area Phase 2',
    ],
  },
  {
    name: 'Chhattisgarh',
    code: 'CG',
    cities: [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Rajnandgaon',
      'Jagdalpur',
      'Raigarh',
      'Ambikapur',
      'Durg',
      'Dhamtari',
      'Mahasamund',
      'Kanker',
      'Kawardha',
      'Janjgir',
      'Champa',
      'Bemetara',
      'Balod',
      'Bhatapara',
      'Kondagaon',
      'Baikunthpur',
      'Mungeli',
    ],
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DN',
    cities: [
      'Daman',
      'Diu',
      'Silvassa',
      'Amli',
      'Naroli',
      'Dadra',
      'Bhimpore',
      'Kadaiya',
      'Samarvarni',
    ],
  },
  {
    name: 'Delhi',
    code: 'DL',
    cities: [
      'New Delhi',
      'Central Delhi',
      'North Delhi',
      'South Delhi',
      'East Delhi',
      'West Delhi',
      'North East Delhi',
      'North West Delhi',
      'South East Delhi',
      'South West Delhi',
      'Shahdara',
      'Dwarka',
      'Rohini',
      'Connaught Place',
      'Karol Bagh',
      'Saket',
      'Vasant Kunj',
      'Janakpuri',
      'Lajpat Nagar',
      'Pitampura',
      'Chandni Chowk',
      'Mayur Vihar',
      'Laxmi Nagar',
      'Hauz Khas',
      'Nehru Place',
      'Paschim Vihar',
    ],
  },
  {
    name: 'Goa',
    code: 'GA',
    cities: [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Cuncolim',
      'Valpoi',
      'Pernem',
      'Quepem',
      'Canacona',
      'Calangute',
      'Candolim',
      'Porvorim',
      'Sanquelim',
    ],
  },
  {
    name: 'Gujarat',
    code: 'GJ',
    cities: [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
      'Navsari',
      'Morbi',
      'Nadiad',
      'Surendranagar',
      'Bharuch',
      'Mehsana',
      'Bhuj',
      'Porbandar',
      'Vapi',
      'Valsad',
      'Godhra',
      'Palanpur',
      'Ankleshwar',
      'Gandhidham',
      'Veraval',
      'Patan',
      'Dahod',
      'Botad',
      'Amreli',
      'Deesa',
      'Jetpur',
      'Gondal',
      'Kalol',
      'Sanand',
    ],
  },
  {
    name: 'Haryana',
    code: 'HR',
    cities: [
      'Gurugram (Gurgaon)',
      'Faridabad',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Sirsa',
      'Bhiwani',
      'Bahadurgarh',
      'Jind',
      'Thanesar (Kurukshetra)',
      'Kaithal',
      'Rewari',
      'Palwal',
      'Jagadhri',
      'Hansi',
      'Narnaul',
      'Fatehabad',
      'Tohana',
      'Narwana',
      'Manesar',
      'Pehowa',
      'Charkhi Dadri',
    ],
  },
  {
    name: 'Himachal Pradesh',
    code: 'HP',
    cities: [
      'Shimla',
      'Dharamshala',
      'Solan',
      'Mandi',
      'Kullu',
      'Manali',
      'Baddi',
      'Palampur',
      'Paonta Sahib',
      'Nahan',
      'Sundernagar',
      'Chamba',
      'Una',
      'Hamirpur',
      'Bilaspur',
      'Kangra',
      'Keylong',
      'Reckong Peo',
      'Nalagarh',
      'Parwanoo',
    ],
  },
  {
    name: 'Jammu and Kashmir',
    code: 'JK',
    cities: [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Kathua',
      'Sopore',
      'Udhampur',
      'Rajouri',
      'Poonch',
      'Kupwara',
      'Pulwama',
      'Ganderbal',
      'Bandipora',
      'Budgam',
      'Kulgam',
      'Shopian',
      'Samba',
      'Reasi',
      'Doda',
      'Ramban',
      'Kishtwar',
      'Akhnoor',
      'Katra',
    ],
  },
  {
    name: 'Jharkhand',
    code: 'JH',
    cities: [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro Steel City',
      'Deoghar',
      'Phusro',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Medininagar (Daltonganj)',
      'Chirkunda',
      'Chaibasa',
      'Jhumri Telaiya',
      'Sahibganj',
      'Dumka',
      'Godda',
      'Gumla',
      'Simdega',
      'Pakur',
      'Lohardaga',
      'Chatra',
      'Jharia',
    ],
  },
  {
    name: 'Karnataka',
    code: 'KA',
    cities: [
      'Bengaluru',
      'Mysuru',
      'Hubballi-Dharwad',
      'Mangaluru',
      'Belagavi',
      'Davanagere',
      'Ballari',
      'Vijayapura',
      'Shivamogga',
      'Tumakuru',
      'Kalaburagi',
      'Udupi',
      'Bidar',
      'Hassan',
      'Gadag-Betageri',
      'Robertsonpet (KGF)',
      'Bhadravati',
      'Chitradurga',
      'Kolar',
      'Mandya',
      'Chikkamagaluru',
      'Gangavati',
      'Ranebennuru',
      'Bagalkote',
      'Haveri',
      'Sirsi',
      'Karwar',
      'Madikeri (Coorg)',
      'Ramanagara',
      'Hosapete',
      'Yadgir',
      'Koppal',
      'Chamarajanagar',
      'Chikkaballapur',
    ],
  },
  {
    name: 'Kerala',
    code: 'KL',
    cities: [
      'Thiruvananthapuram',
      'Kochi (Ernakulam)',
      'Kozhikode',
      'Thrissur',
      'Kollam',
      'Kannur',
      'Alappuzha',
      'Palakkad',
      'Kottayam',
      'Malappuram',
      'Kasaragod',
      'Pathanamthitta',
      'Idukki',
      'Wayanad (Kalpetta)',
      'Thalassery',
      'Ponnani',
      'Vatakara',
      'Kanhangad',
      'Payyanur',
      'Tirur',
      'Perinthalmanna',
      'Kothamangalam',
      'Chalakudy',
      'Neyyattinkara',
      'Aluva',
      'Cherthala',
      'Changanassery',
      'Muvattupuzha',
      'Manjeri',
      'Guruvayur',
    ],
  },
  {
    name: 'Ladakh',
    code: 'LA',
    cities: [
      'Leh',
      'Kargil',
      'Diskit',
      'Nubra Valley',
      'Dras',
      'Padum (Zanskar)',
      'Khaltsi',
      'Nyoma',
      'Sankoo',
    ],
  },
  {
    name: 'Lakshadweep',
    code: 'LD',
    cities: [
      'Kavaratti',
      'Agatti',
      'Amini',
      'Andrott',
      'Minicoy',
      'Kalpeni',
      'Kiltan',
      'Chetlat',
      'Kadmat',
      'Bitra',
    ],
  },
  {
    name: 'Madhya Pradesh',
    code: 'MP',
    cities: [
      'Indore',
      'Bhopal',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Murwara (Katni)',
      'Singrauli',
      'Burhanpur',
      'Khandwa',
      'Bhind',
      'Chhindwara',
      'Guna',
      'Shivpuri',
      'Vidisha',
      'Chhatarpur',
      'Damoh',
      'Mandsaur',
      'Khargone',
      'Neemuch',
      'Pithampur',
      'Hoshangabad (Narmadapuram)',
      'Itarsi',
      'Sehore',
      'Betul',
      'Seoni',
      'Datia',
      'Nagda',
      'Morena',
      'Dhar',
    ],
  },
  {
    name: 'Maharashtra',
    code: 'MH',
    cities: [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Pimpri-Chinchwad',
      'Nashik',
      'Kalyan-Dombivli',
      'Vasai-Virar',
      'Navi Mumbai',
      'Chhatrapati Sambhajinagar (Aurangabad)',
      'Solapur',
      'Mira-Bhayandar',
      'Bhiwandi-Nizampur',
      'Amravati',
      'Nanded',
      'Kolhapur',
      'Akola',
      'Ulhasnagar',
      'Sangli-Miraj-Kupwad',
      'Malegaon',
      'Jalgaon',
      'Latur',
      'Dhule',
      'Ahmednagar',
      'Chandrapur',
      'Parbhani',
      'Ichalkaranji',
      'Jalna',
      'Ambarnath',
      'Panvel',
      'Bhusawal',
      'Ratnagiri',
      'Satara',
      'Beed',
      'Yavatmal',
      'Gondia',
      'Wardha',
      'Barshi',
      'Achalpur',
      'Osmanabad (Dharashiv)',
      'Nandurbar',
      'Shirdi',
      'Palghar',
      'Sindhudurg',
    ],
  },
  {
    name: 'Manipur',
    code: 'MN',
    cities: [
      'Imphal',
      'Thoubal',
      'Kakching',
      'Ukhrul',
      'Churachandpur',
      'Bishnupur',
      'Senapati',
      'Tamenglong',
      'Chandel',
      'Kangpokpi',
      'Jiribam',
      'Moreh',
      'Mayang Imphal',
    ],
  },
  {
    name: 'Meghalaya',
    code: 'ML',
    cities: [
      'Shillong',
      'Tura',
      'Jowai',
      'Nongpoh',
      'Williamnagar',
      'Baghmara',
      'Resubelpara',
      'Mairang',
      'Cherrapunji (Sohra)',
      'Khliehriat',
      'Ampati',
      'Mawkyrwat',
    ],
  },
  {
    name: 'Mizoram',
    code: 'MZ',
    cities: [
      'Aizawl',
      'Lunglei',
      'Saiha',
      'Champhai',
      'Kolasib',
      'Serchhip',
      'Lawngtlai',
      'Mamit',
      'Hnahthial',
      'Saitual',
      'Khawzawl',
    ],
  },
  {
    name: 'Nagaland',
    code: 'NL',
    cities: [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
      'Mon',
      'Phek',
      'Kiphire',
      'Longleng',
      'Peren',
      'Chumoukedima',
      'Niuland',
      'Tseminyu',
      'Noklak',
      'Shamator',
    ],
  },
  {
    name: 'Odisha',
    code: 'OD',
    cities: [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Berhampur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
      'Bargarh',
      'Jeypore',
      'Angul',
      'Dhenkanal',
      'Rayagada',
      'Paradip',
      'Bolangir',
      'Kendrapara',
      'Jagatsinghpur',
      'Bhawanipatna',
      'Jatani',
      'Byasanagar',
      'Sundargarh',
      'Keonjhar',
    ],
  },
  {
    name: 'Puducherry',
    code: 'PY',
    cities: [
      'Puducherry',
      'Karaikal',
      'Mahe',
      'Yanam',
      'Ozhukarai',
      'Villianur',
      'Ariyankuppam',
      'Bahour',
      'Lawspet',
      'Muthialpet',
    ],
  },
  {
    name: 'Punjab',
    code: 'PB',
    cities: [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'SAS Nagar (Mohali)',
      'Hoshiarpur',
      'Batala',
      'Pathankot',
      'Moga',
      'Abohar',
      'Malerkotla',
      'Khanna',
      'Muktsar',
      'Barnala',
      'Firozpur',
      'Kapurthala',
      'Phagwara',
      'Rajpura',
      'Zirakpur',
      'Mansa',
      'Sangrur',
      'Fazilka',
      'Gurdaspur',
      'Nawanshahr',
      'Tarn Taran',
      'Rupnagar (Ropar)',
    ],
  },
  {
    name: 'Rajasthan',
    code: 'RJ',
    cities: [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sikar',
      'Pali',
      'Sri Ganganagar',
      'Beawar',
      'Hanumangarh',
      'Tonk',
      'Kishangarh',
      'Jhunjhunu',
      'Sawai Madhopur',
      'Chittorgarh',
      'Bundi',
      'Baran',
      'Nagaur',
      'Makrana',
      'Sujangarh',
      'Dhaulpur',
      'Gangapur City',
      'Hindaun',
      'Bhiwadi',
      'Barmer',
      'Jaisalmer',
      'Churu',
      'Banswara',
      'Rajsamand',
      'Dausa',
      'Abu Road',
    ],
  },
  {
    name: 'Sikkim',
    code: 'SK',
    cities: [
      'Gangtok',
      'Namchi',
      'Geyzing',
      'Mangan',
      'Rangpo',
      'Singtam',
      'Jorethang',
      'Ravangla',
      'Pakyong',
      'Soreng',
      'Yuksom',
    ],
  },
  {
    name: 'Tamil Nadu',
    code: 'TN',
    cities: [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Tirunelveli',
      'Thoothukudi',
      'Dindigul',
      'Thanjavur',
      'Ranipet',
      'Sivakasi',
      'Virudhunagar',
      'Kanchipuram',
      'Karur',
      'Nagercoil',
      'Hosur',
      'Cuddalore',
      'Kumbakonam',
      'Tiruvannamalai',
      'Pollachi',
      'Rajapalayam',
      'Pudukkottai',
      'Nagapattinam',
      'Theni',
      'Namakkal',
      'Villupuram',
      'Krishnagiri',
      'Chengalpattu',
      'Tenkasi',
      'Mayiladuthurai',
      'Tiruvarur',
      'Ramanathapuram',
      'Ariyalur',
      'Perambalur',
      'Nilgiris (Ooty)',
      'Kallakurichi',
      'Tirupathur',
      'Avadi',
      'Tambaram',
      'Kovilpatti',
      'Ambur',
      'Vaniyambadi',
      'Attur',
      'Paramakudi',
      'Arakkonam',
      'Neyveli',
      'Bodinayakanur',
      'Pattukkottai',
    ],
  },
  {
    name: 'Telangana',
    code: 'TS',
    cities: [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Ramagundam',
      'Khammam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Siddipet',
      'Suryapet',
      'Miryalaguda',
      'Jagtial',
      'Nirmal',
      'Sircilla',
      'Kamareddy',
      'Kothagudem',
      'Mancherial',
      'Wanaparthy',
      'Gadwal',
      'Medak',
      'Sangareddy',
      'Vikarabad',
      'Jangaon',
      'Bhongir',
      'Palwancha',
      'Bodhan',
      'Tandur',
      'Koratla',
    ],
  },
  {
    name: 'Tripura',
    code: 'TR',
    cities: [
      'Agartala',
      'Dharmanagar',
      'Udaipur',
      'Kailashahar',
      'Teliamura',
      'Khowai',
      'Belonia',
      'Melaghar',
      'Ambassa',
      'Sabroom',
      'Santirbazar',
      'Kumarghat',
      'Bishalgarh',
      'Ranirbazar',
    ],
  },
  {
    name: 'Uttar Pradesh',
    code: 'UP',
    cities: [
      'Lucknow',
      'Kanpur',
      'Varanasi',
      'Agra',
      'Prayagraj (Allahabad)',
      'Ghaziabad',
      'Noida',
      'Greater Noida',
      'Meerut',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Firozabad',
      'Jhansi',
      'Muzaffarnagar',
      'Mathura',
      'Rampur',
      'Shahjahanpur',
      'Farrukhabad',
      'Ayodhya (Faizabad)',
      'Sambhal',
      'Amroha',
      'Hapur',
      'Hardoi',
      'Fatehpur',
      'Raebareli',
      'Orai',
      'Sitapur',
      'Bahraich',
      'Modinagar',
      'Unnao',
      'Jaunpur',
      'Lakhimpur',
      'Hathras',
      'Banda',
      'Pilibhit',
      'Barabanki',
      'Mirzapur',
      'Bulandshahr',
      'Etawah',
      'Mainpuri',
      'Deoria',
      'Badaun',
      'Ghazipur',
      'Basti',
      'Sultanpur',
      'Ballia',
      'Gonda',
      'Kasganj',
      'Shamli',
      'Lalitpur',
      'Bijnor',
    ],
  },
  {
    name: 'Uttarakhand',
    code: 'UK',
    cities: [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani',
      'Rudrapur',
      'Kashipur',
      'Rishikesh',
      'Nainital',
      'Pithoragarh',
      'Ramnagar',
      'Manglaur',
      'Jaspur',
      'Kichha',
      'Kotdwar',
      'Tehri',
      'Almora',
      'Mussoorie',
      'Chamoli (Gopeshwar)',
      'Uttarkashi',
      'Pauri',
      'Champawat',
      'Bageshwar',
      'Rudraprayag',
      'Vikasnagar',
    ],
  },
  {
    name: 'West Bengal',
    code: 'WB',
    cities: [
      'Kolkata',
      'Howrah',
      'Asansol',
      'Siliguri',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
      'Dankuni',
      'Dhulian',
      'Ranaghat',
      'Haldia',
      'Raiganj',
      'Krishnanagar',
      'Nabadwip',
      'Midnapore',
      'Jalpaiguri',
      'Balurghat',
      'Basirhat',
      'Bankura',
      'Darjeeling',
      'Alipurduar',
      'Purulia',
      'Cooch Behar',
      'Diamond Harbour',
      'Barasat',
      'Barrackpore',
      'Bongaon',
      'Tamluk',
      'Suri',
      'Bolpur (Santiniketan)',
      'Kalimpong',
      'Serampore',
      'Chandannagar',
    ],
  },
];

export async function seedLocations() {
  console.log('📍 Seeding All India States and Cities (28 States & 8 Union Territories)...');

  // 1. Fetch existing states
  const existingStates = await db.query.states.findMany();
  const stateMap = new Map<string, typeof states.$inferSelect>();
  existingStates.forEach((st) => {
    stateMap.set(st.code, st);
  });

  let totalStatesAdded = 0;
  let totalCitiesAdded = 0;

  for (const item of ALL_INDIA_LOCATIONS) {
    let stateRow = stateMap.get(item.code);

    if (!stateRow) {
      const [inserted] = await db
        .insert(states)
        .values({
          name: item.name,
          code: item.code,
          isActive: true,
        })
        .returning();
      stateRow = inserted;
      stateMap.set(item.code, inserted);
      totalStatesAdded++;
      console.log(`  ➕ Added State: ${item.name} (${item.code})`);
    }

    // Fetch existing cities for this state
    const existingCities = await db.query.cities.findMany({
      where: eq(cities.stateId, stateRow.id),
    });
    const existingCityNames = new Set(existingCities.map((c) => c.name.toLowerCase()));

    const newCitiesToInsert = item.cities
      .filter((cityName) => !existingCityNames.has(cityName.toLowerCase()))
      .map((cityName) => ({
        stateId: stateRow!.id,
        name: cityName,
        isActive: true,
      }));

    if (newCitiesToInsert.length > 0) {
      await db.insert(cities).values(newCitiesToInsert);
      totalCitiesAdded += newCitiesToInsert.length;
    }
  }

  console.log(
    `✅ Seeding summary: Added ${totalStatesAdded} states, ${totalCitiesAdded} cities. All 36 Indian States & UTs are active.`
  );

  // 3. Seed Sample Delivery Partners in Tamil Nadu if none exist
  const tnState = stateMap.get('TN') || (await db.query.states.findFirst({ where: eq(states.code, 'TN') }));

  if (tnState) {
    const cbeCity = await db.query.cities.findFirst({
      where: (c, { and, eq }) => and(eq(c.stateId, tnState.id), eq(c.name, 'Coimbatore')),
    });
    const chennaiCity = await db.query.cities.findFirst({
      where: (c, { and, eq }) => and(eq(c.stateId, tnState.id), eq(c.name, 'Chennai')),
    });
    const sivakasiCity = await db.query.cities.findFirst({
      where: (c, { and, eq }) => and(eq(c.stateId, tnState.id), eq(c.name, 'Sivakasi')),
    });

    const samplePartners = [
      {
        name: 'Senthil Kumar Express Cargo',
        whatsappNumber: '919842100001',
        mobileNumber: '9842100001',
        email: 'senthil.express@gmail.com',
        stateId: tnState.id,
        cityId: cbeCity?.id || 1,
        address: '142 Cross Cut Road, Gandhipuram',
        pincode: '641012',
        vehicleType: 'Mini Truck (Tata Ace)',
        vehicleNumber: 'TN 38 BX 4452',
        notes: 'Specialized in bulk parcel delivery across Coimbatore & Tiruppur micro-markets.',
        status: 'ACTIVE' as const,
      },
      {
        name: 'Muthu Vel Logistics',
        whatsappNumber: '919842100002',
        mobileNumber: '9842100002',
        email: 'muthuvel.logistics@gmail.com',
        stateId: tnState.id,
        cityId: chennaiCity?.id || 1,
        address: '58 Koyambedu Wholesale Market Complex',
        pincode: '600107',
        vehicleType: 'Delivery Van',
        vehicleNumber: 'TN 02 AB 8974',
        notes: 'Covering Central, North & South Chennai zones.',
        status: 'ACTIVE' as const,
      },
      {
        name: 'Sivakasi Fast Transports',
        whatsappNumber: '919842100003',
        mobileNumber: '9842100003',
        email: 'sivakasi.fast@gmail.com',
        stateId: tnState.id,
        cityId: sivakasiCity?.id || 1,
        address: '12 Bypass Road, Sivakasi',
        pincode: '626123',
        vehicleType: 'Eicher Truck',
        vehicleNumber: 'TN 84 D 3312',
        notes: 'Factory direct dispatches and regional hub transfers.',
        status: 'ACTIVE' as const,
      },
    ];

    for (const p of samplePartners) {
      const exists = await db.query.deliveryPartners.findFirst({
        where: eq(deliveryPartners.mobileNumber, p.mobileNumber),
      });
      if (!exists) {
        await db.insert(deliveryPartners).values(p);
        console.log(`  🚚 Added Sample Delivery Partner: ${p.name}`);
      }
    }
  }

  console.log('🎉 Location & Delivery Partner database seeding completed!');
}

if (require.main === module || process.argv[1]?.includes('seed-locations')) {
  seedLocations()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('❌ Seeding error:', err);
      process.exit(1);
    });
}
